### ISSUE TITLE
ember deploy:list prod lists nothing

### ISSUE THREAD

**Issue by bartocc** [ember-cli-deploy/ember-cli-deploy-display-revisions#2]
I just deployed successfully in prod.
I can see a valid manifest_id in redis and my assets are present in S3.

But `ember deploy:list prod` does not return anything.

console output gist here
https://gist.github.com/bartocc/29e0a3455203c394a160

**Comment by duizendnegen** [comment]
display-revisions depends on the redis or other index adapters returning a list of old revisions - this might not have happened. Which version of which redis plugin are you using?

**Comment by bartocc** [comment]
@duizendnegen I'm using `ember-cli-deploy-lightning-pack@0.1.3` wich references `github:zapnito/ember-cli-deploy-redis#092c1164163168415b21a8e6286dbfd5d0fa78b8` I believe

**Comment by duizendnegen** [comment]
Seems that you're using an outdated version of `ember-cli-deploy-lightning-pack`. The referenced https://github.com/zapnito/ember-cli-deploy-redis/tree/092c1164163168415b21a8e6286dbfd5d0fa78b8 doesn't include `fetchRevisions`, which gives `list` an empty list to display.
If you install `ember-cli-deploy-lightning-pack` 0.2.0-beta.5 you should be set.
