### ISSUE TITLE
List displays `Invalid DateTime` for Deploy time column

### ISSUE THREAD

**Issue by ddoria921** [ember-cli-deploy/ember-cli-deploy-display-revisions#69]
I'm running into an issue where the table displays `Invalid DateTime` for Deploy time column. I traced the issue down to [this line](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/blob/9e67102fae10f44cc6092c6f6ed7f5a29a68e897/lib/scm-table.js#L75). It seems like `ember-cli-deploy-revision-data` is storing the the [timestamp as an ISO date string](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/blob/40613adc3cdaeb962f3b71294482ef01130f614e/lib/scm-data-generators/git.js#L34). 

I followed along in [this PR](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/pull/41) and noticed the prior implementation worked with ISO strings but was [later changed to deal with Date objects](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/pull/42) after someone else reported a similar "Invalid DateTime" issue. In their case they were running on the 1.x.x line of `ember-cli-deploy-revision-data` (the 2.x line wasn't out yet) which might be why it worked then and is now breaking on the latest version. 

I was able to fix the issue by downgrading to from `2.1.2` -> `2.1.1` 

## Steps to Reproduce
1. Install `ember-cli-deploy-revision-data@2.0.0` 
2. Install `ember-cli-deploy-display-revisions@2.1.2`
3. Use the default config for both plugins 
4. Run a deploy and display revisions

**Comment by lukemelia** [comment]
Thanks for the excellent bug report @ddoria921. I realistically won't have time to address this myself in the near future, but am happy to review and merge a PR addressing this situation.

**Comment by ddoria921** [comment]
I'm happy to put together a PR this week that works with both ISO date strings and Date objects. That should get it working with the latest and yet still be backwards compatible.

**Comment by lukemelia** [comment]
Sounds good @ddoria921

**Comment by ddoria921** [comment]
Fixed by #70
