### ISSUE TITLE
Q: display revision in APP

### ISSUE THREAD

**Issue by basz** [ember-cli-deploy/ember-cli-deploy-display-revisions#9]
More a question then an issue;

would it be possible to display the revision inside the running app? If so, what would be the best route to do that?

**Comment by duizendnegen** [comment]
One possibility would be to integrate this in the serving of your index.html.
For that there are two routes:
a. like `ember-cli-deploy-sentry`, after building, edit the index.html and add in a meta tag, like https://github.com/dschmidt/ember-cli-deploy-sentry/blob/master/index.js#L66
b. edit the content in the serving of your index.html, in your node / C# / whatever server arch infrastructure, i.e. adding at https://gist.github.com/duizendnegen/85b5c4a7b7eef28f0756#file-homecontroller-cs-L21:
```cs
var split = content.Split(new[] { "</head>" },
   StringSplitOptions.RemoveEmptyEntries);

var version = "abc123"; // get this from your redis / azure tables / whatever

var injection = string.Format("<meta name=\"my-app:version\" content=\"{0}\"></meta>", version);

var builder = new StringBuilder();
builder.Append(split[0]);
builder.Append(injection);
builder.Append("</head>");
builder.Append(split[1]);
var result = builder.ToString();

retun result;
```

**Comment by basz** [comment]
I went for a simple php script that parses index.html:x.x.x-xxxxxxxx files, finds the most recent one one and returned it as Json string. The app gets that. Works.

Thanks
